name: Update Badges

on:
  push:
    branches: [ master, main ]
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Get test coverage
      id: coverage
      run: |
        if [ -f backend/coverage/coverage-summary.json ]; then
          COVERAGE=$(cat backend/coverage/coverage-summary.json | jq -r '.total.lines.pct')
          echo "COVERAGE=$COVERAGE" >> $GITHUB_OUTPUT
        fi
